import glob

ART_PATTERN = "album/*.jpg"

rule = "\n---------------"

TITLE_RE = r"[\/](.+).*\]"
GH_RAW = 'https://raw.githubusercontent.com/lfender6445/art/master/album/'

def markdown_image(img):
    return f"![{img}]({img})"

def title():
    return """
# art by luke fender
this readme was autogenerated by [a python script](make_readme.py)
{rule}
    """.format(rule=rule)

def markdown_title(img):
    title = img.split('/')[1]
    print('making title', title)
    return f"## [{title}]({GH_RAW}{title})"

def make_readme():
    file_handle = open('README.md', 'w')

    file_handle.write(title())

    entries = []

    for img in glob.glob(ART_PATTERN):
        entries.append({
            'img': markdown_image(img),
            'title': markdown_title(img),
        })
    print(entries)

    for entry in entries:
        file_handle.write(f"\n{entry['title']}")
        file_handle.write(f"\n{entry['img']}")
        file_handle.write(rule)

    file_handle.close()

if __name__ == '__main__':
    make_readme()
