#!/usr/bin/python3
import glob
import subprocess
from datetime import datetime

ART_PATTERN = "album/*.jpg"

rule = "\n---------------"

TITLE_RE = r"[\/](.+).*\]"
GH_RAW = 'https://raw.githubusercontent.com/lfender6445/art/master/album/'


def du(path):
    """disk usage in human readable format (e.g. '2,1GB')"""
    return subprocess.check_output(['du','-sh', path]).split()[0].decode('utf-8')

def markdown_image(img):
    return f"![{img}]({img})"

def title():
    return """
# art by luke fender
this readme was autogenerated by [a python script](make_readme.py)
{rule}
    """.format(rule=rule)

def markdown_title(img):
    title = img.split('/')[1]
    return f"## [{title}]({GH_RAW}{title})"

def size():
    return f"\n - size: {du('./album')}"

def last_run():
    return f'\n - last run: {datetime.now().strftime("%Y-%b-%d, %A %I:%M:%S")}'

def make_readme():
    file_handle = open('README.md', 'w')

    file_handle.write(title())
    file_handle.write(size())
    file_handle.write(last_run())
    file_handle.write(rule)

    entries = []

    for img in glob.glob(ART_PATTERN):
        entries.append({
            'img': markdown_image(img),
            'title': markdown_title(img),
        })

    for entry in entries:
        file_handle.write(f"\n{entry['title']}")
        file_handle.write(f"\n{entry['img']}")
        file_handle.write(rule)

    file_handle.close()

if __name__ == '__main__':
    make_readme()
